### ISSUE TITLE
Full Page Cache not working in 1.5

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#1737]
`ArgumentCountError: Too few arguments to function Thirtybees\Core\View\Model\ProductViewModelCore::__construct(), 2 passed in classes/PageCacheEntry.php on line 271 and exactly 4 expected`

Location:
`classes/view/model/ProductViewModel.php line 27`
